import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainPage from './actualpages/Main'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <html lang='eng'></html>
        <title>
            ArcadeChess
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <MainPage />
    </div>
  )
}

export default Home
