import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import MainPage from './actualpages/Main'

const Home: NextPage = () => {
  const [imagechange,setimagechange]=useState<string>("wr");


 const imagechangehandler=(arg:string):void=>{
  setimagechange(arg);
 }


  return (
    <div className={styles.container}>
      <Head>
     
        <title>
            ArcadeChessy
        </title>
        <link rel="icon" href={`/${imagechange}.png`} />
        <meta name="description" content="Generated by create next app" />
     
      
      </Head>

      <MainPage handler={imagechangehandler} />
    </div>
  )
}

export default Home;
